export const LOAD_QUESTION_SUCCESS = "LOAD_QUESTION_SUCCESS";
export const LOAD_QUESTION_FAILURE = "LOAD_QUESTION_FAILURE";

export const ADD_SCORE = "ADD_SCORE";
export const RESET_SCORE = "RESET_SCORE";

export const SET_LEVELS = "SET_LEVELS";