export const LOAD_QUESTION_SUCCESS = "LOAD_QUESTION_SUCCESS";
export const LOAD_QUESTION_FAILURE = "LOAD_QUESTION_FAILURE";

export const MARK_ANSWER_SELECTED = "MARK_ANSWER_SELECTED";
export const MARK_ANSWER_CORRECT = "MARK_ANSWER_CORRECT";
export const MARK_ANSWER_WRONG = "MARK_ANSWER_WRONG";

export const ADD_SCORE = "ADD_SCORE";
export const RESET_SCORE = "RESET_SCORE";

export const SET_LEVELS = "SET_LEVELS";

export const INIT_GAME = "INIT_GAME";
export const START_GAME = "START_GAME";
export const LOSE_GAME = "LOST_GAME";
export const WIN_GAME = "WIN_GAME";

export const ADVANCE_CURRENT_LEVEL = "ADVANCE_LEVEL";
export const RESET_CURRENT_LEVEL = "RESET_LEVEL";

export const SET_USER_INFO = "SET_USER_ID";