language: node_js
node_js: 8

before_install: export DISPLAY=:99.0
install: yarn install

script:
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  - sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
  - sudo apt-get update -qq
  - sudo apt-get install -qq google-chrome-stable
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - node_modules/karma/bin/karma start karma.conf.js --single-run