language: node_js
node_js: 8

addons:
  chrome: stable

install: yarn install

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

script:
  - node_modules/karma/bin/karma start karma.conf.js --single-run